name: "Feature Request"
description: "Request a new feature for TourGuide"
title: "[Feature]: "
labels: enhancement
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out a feature request! Due to limited developer resources, we cannot guarantee we will fulfill your request at major speed. But we'll do our best!
  - type: textarea
    id: whats-the-request
    attributes:
      label: "What's the request?"
      description: "Tell us the basic behavior that TourGuide doesn't currently do that you'd love to see. The more detail you can give, the better -- any similar pieces of the codebase, any tiles that are similar to a newly proposed tile, the reasons why this would improve TourGuide, et cetera."
      placeholder: Tell us what you want to see!
  - type: dropdown
    id: user-state
    attributes:
      label: Account State
      description: "Is this feature most helpful for a specific account state?"
      options:
        - "Standard (In-Run)"
        - "Unrestricted (In-Run)"
        - "Aftercore"
        - "All account states would benefit equally!"
  - type: input
    id: commit-version
    attributes:
      label: Your current TourGuide version
      description: Please paste your current TourGuide Commit hash, via `ash git_info("tourguide")` in the CLI.
      placeholder: ex. "925e68c5af96edd52b482887aa07758c5284dc47"
