name: Sync Bundled-main to testing

on:
  workflow_run:
    workflows: [bundle ASH script(s), and push to new branch]
    types: [completed]
  workflow_dispatch:
permissions:
  contents: write

jobs:
  sync-branch:
    name: Sync Bundled-main to testing branch
    runs-on: ubuntu-latest
    steps:
      # See https://github.com/connor-baer/action-sync-branch
      # GitHub recommends pinning the SHA for security:
      # https://docs.github.com/en/actions/security-guides/security-hardening-for-github-actions#using-third-party-actions
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: Bundled-main
      - uses: connor-baer/action-sync-branch@b54ed9b2c68941d1b2974a7776dc8e3d7d14073c
        with:
          branch: testing
          token: ${{ secrets.GITHUB_TOKEN }}
          force: false
